backend:
  name: git-gateway
  branch: master

media_folder: "images"
public_folder: "/images"

site_url: ""
logo_url: "/polodelleeta.png"

collections:
  - name: "pages"
    label: "Pagine"
    label_singular: "Pagina"
    folder: "it"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base" }
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", hint: "Esempio: /nome-pagina/" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
